import { Member, PlanData, SiteContent, AccessLog } from './types';

export const ADMIN_MASTER_QR_VALUE = 'OAGYM_ADMIN_SUPER_KEY_AUTH_2026_X98';
export const ADMIN_DEFAULT_PIN = 'OAGYM2026';

export const INITIAL_PLANS: PlanData[] = [
  {
    id: 'inscripcion',
    name: 'Inscripción (Pago único)',
    category: 'inscripcion',
    price: 10,
    formattedPrice: '$10',
    duration: 'Pago único',
    description: 'Registro en el sistema. Activado.',
    recommended: false,
    features: [
      'Registro oficial en el sistema de OA GYM',
      'Activación de cuenta y perfil de socio',
      'Carnet digital inteligente con código QR',
      'Habilitado para asignación de planes y rutinas',
    ],
  },
  {
    id: 'mensualidad-base',
    name: 'Mensualidad Base',
    category: 'base',
    price: 35,
    formattedPrice: '$35',
    duration: 'Activo por 30 días',
    description: 'Acceso libre al gimnasio + Nutrición básica inicial o Entrenamiento básico inicial + 1 semana de monitor.',
    recommended: false,
    features: [
      'Acceso libre al gimnasio',
      'Nutrición básica inicial o Entrenamiento básico inicial',
      '1 semana de monitor',
      'Activo por 30 días',
    ],
  },
  {
    id: 'plan-nutricional-detallado',
    name: 'Plan Nutricional Detallado',
    category: 'nutricion',
    price: 40,
    pricePrefix: '+',
    formattedPrice: '+$40',
    duration: 'Hereda mensualidad',
    description: 'Plan de alimentación avanzado y personalizado. Hereda mensualidad.',
    recommended: false,
    features: [
      'Plan de alimentación avanzado y personalizado',
      'Cálculo calórico y macronutrientes individualizado',
      'Pautas de suplementación y optimización metabólica',
      'Hereda mensualidad de tu suscripción activa',
    ],
  },
  {
    id: 'plan-entrenamiento-detallado',
    name: 'Plan Entrenamiento Detallado',
    category: 'entrenamiento',
    price: 40,
    pricePrefix: '+',
    formattedPrice: '+$40',
    duration: 'Hereda mensualidad',
    description: 'Plan de ejercicios avanzado + Acompañamiento continuo de monitor. Hereda mensualidad.',
    recommended: false,
    features: [
      'Plan de ejercicios avanzado',
      'Acompañamiento continuo de monitor',
      'Biomecánica aplicada y sobrecarga progresiva',
      'Hereda mensualidad de tu suscripción activa',
    ],
  },
  {
    id: 'plan-personalizado-premium',
    name: 'Plan Personalizado Premium',
    category: 'personalizado',
    price: 80,
    pricePrefix: '+',
    formattedPrice: '+$80',
    duration: 'Hereda mensualidad',
    description: 'Todo incluido: Ajuste a hábitos/deportes + Nutrición detallada + Entrenamiento especializado.',
    recommended: true,
    features: [
      'Todo incluido: Acceso total al gimnasio',
      'Ajuste a hábitos / deportes específicos',
      'Nutrición detallada y personalizada',
      'Entrenamiento especializado y guiado 1 a 1',
    ],
  },
];

export const INITIAL_SITE_CONTENT: SiteContent = {
  gymName: 'OA GYM',
  slogan: 'Fuerza, Disciplina & Evolución Constante',
  announcement: '',
  showAnnouncement: false,
  phone: '+58 0424-8543500',
  whatsapp: '584248543500',
  address: 'Avenida Principal Las Vegas de Táriba',
  scheduleWeekdays: 'Lunes a Viernes: 5:00 AM - 9:00 PM',
  scheduleWeekends: '',
  heroHeadline: 'CONSTRUYE TU MEJOR VERSIÓN CON CIENCIA Y DISCIPLINA',
  heroSubheadline: 'En OA GYM unificamos biomecánica de alta gama, entrenamiento inteligente y seguimiento antropométrico en tiempo real para que cada gota de esfuerzo se traduzca en resultados reales.',
  aboutText: 'OA GYM nació con la convicción de eliminar el entrenamiento improvisado. Nuestras instalaciones cuentan con maquinaria de carga guiada de última generación, área de peso libre con plataformas de levantamiento olímpico, zona funcional de alta intensidad y un equipo multidisciplinar de preparadores físicos y nutricionistas certificados.',
};

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mem_1',
    cedula: '1020304050',
    name: 'Carlos Andrés Rodríguez',
    phone: '3104567890',
    email: 'carlos.rodriguez@email.com',
    birthDate: '1994-06-15',
    planId: 'plan-personalizado-premium',
    planName: 'Plan Personalizado Premium',
    membershipStart: '2026-09-01',
    membershipEnd: '2026-10-16',
    daysRemaining: 24,
    status: 'active',
    assignedTrainer: 'Prof. Óscar Arias (Head Coach)',
    emergencyContact: 'Luisa Rodríguez (Hermana)',
    emergencyPhone: '3119876543',
    bloodType: 'O+',
    routineTitle: 'Fase 3: Hipertrofia & Fuerza Específica (Torso/Pierna)',
    routineGoals: 'Aumento de masa magra en tren superior (+2.5 kg) y reducción de grasa visceral.',
    nutritionOverview: 'Dieta hiperproteica 2.2g/kg, superávit controlado de 300 kcal, hidratación 3.5L/día.',
    records: [
      {
        id: 'rec_1_1',
        memberId: 'mem_1',
        date: '2026-06-10',
        weightKg: 82.5,
        heightCm: 178,
        bodyFatPct: 19.8,
        muscleMassKg: 38.2,
        chestCm: 101,
        waistCm: 89,
        bicepCm: 35.5,
        notes: 'Inicio de preparación. Buena movilidad de cadera, leve limitación en dorsiflexión de tobillo.',
        evaluator: 'Lic. Óscar Arias',
      },
      {
        id: 'rec_1_2',
        memberId: 'mem_1',
        date: '2026-07-15',
        weightKg: 81.2,
        heightCm: 178,
        bodyFatPct: 18.1,
        muscleMassKg: 38.9,
        chestCm: 102,
        waistCm: 86.5,
        bicepCm: 36.2,
        notes: 'Disminución notable del perímetro abdominal. Incremento en RPE en sentadilla libre.',
        evaluator: 'Lic. Óscar Arias',
      },
      {
        id: 'rec_1_3',
        memberId: 'mem_1',
        date: '2026-08-20',
        weightKg: 80.6,
        heightCm: 178,
        bodyFatPct: 16.4,
        muscleMassKg: 39.7,
        chestCm: 103.5,
        waistCm: 84.0,
        bicepCm: 37.0,
        notes: 'Excelente adherencia al bloque de hipetrofia. Aumento de 800g de masa muscular.',
        evaluator: 'Lic. Óscar Arias',
      },
      {
        id: 'rec_1_4',
        memberId: 'mem_1',
        date: '2026-09-18',
        weightKg: 79.8,
        heightCm: 178,
        bodyFatPct: 15.2,
        muscleMassKg: 40.4,
        chestCm: 104.5,
        waistCm: 82.0,
        bicepCm: 37.6,
        notes: 'Estado actual: Óptimo tono muscular y definición en deltoides. Mantener cargas progresivas.',
        evaluator: 'Lic. Óscar Arias',
      },
    ],
    payments: [
      {
        id: 'pay_1_1',
        memberId: 'mem_1',
        memberName: 'Carlos Andrés Rodríguez',
        amount: 80,
        date: '2026-09-01',
        daysAdded: 30,
        method: 'Tarjeta',
        receiptNumber: 'REC-2026-0891',
        notes: 'Renovación mensual Plan Personalizado Premium',
      },
    ],
  },
  {
    id: 'mem_2',
    cedula: '1098765432',
    name: 'Mariana Gómez Serna',
    phone: '3157891234',
    email: 'mariana.gomez@email.com',
    birthDate: '1998-11-23',
    planId: 'mensualidad-base',
    planName: 'Mensualidad Base',
    membershipStart: '2026-08-27',
    membershipEnd: '2026-09-27',
    daysRemaining: 5,
    status: 'expiring',
    assignedTrainer: 'Entr. Camilo Torres',
    emergencyContact: 'Felipe Gómez (Padre)',
    emergencyPhone: '3168899001',
    bloodType: 'A+',
    routineTitle: 'Fase 2: Tonificación Global & Condición Metabólica',
    routineGoals: 'Acondicionamiento físico general, fortalecimiento de core y flexibilidad isquiosural.',
    nutritionOverview: 'Pautas de alimentación normocalórica con énfasis en fuentes no procesadas.',
    records: [
      {
        id: 'rec_2_1',
        memberId: 'mem_2',
        date: '2026-07-28',
        weightKg: 64.0,
        heightCm: 165,
        bodyFatPct: 26.5,
        muscleMassKg: 24.8,
        chestCm: 88,
        waistCm: 72,
        bicepCm: 26,
        notes: 'Valoración inicial. Buena técnica en sentadilla goblet y empujes.',
        evaluator: 'Entr. Camilo Torres',
      },
      {
        id: 'rec_2_2',
        memberId: 'mem_2',
        date: '2026-08-27',
        weightKg: 62.8,
        heightCm: 165,
        bodyFatPct: 24.9,
        muscleMassKg: 25.3,
        chestCm: 88,
        waistCm: 69.5,
        bicepCm: 26.5,
        notes: 'Reducción de cintura (-2.5 cm). Notoria mejora de resistencia en intervalos aeróbicos.',
        evaluator: 'Entr. Camilo Torres',
      },
    ],
    payments: [
      {
        id: 'pay_2_1',
        memberId: 'mem_2',
        memberName: 'Mariana Gómez Serna',
        amount: 35,
        date: '2026-08-27',
        daysAdded: 30,
        method: 'Transferencia',
        receiptNumber: 'REC-2026-0742',
        notes: 'Mensualidad Base (30 días)',
      },
    ],
  },
  {
    id: 'mem_3',
    cedula: '1040506070',
    name: 'Andrés Felipe Morales',
    phone: '3209871122',
    email: 'andres.morales@email.com',
    birthDate: '1991-03-08',
    planId: 'mensualidad-base',
    planName: 'Mensualidad Base',
    membershipStart: '2026-08-10',
    membershipEnd: '2026-09-10',
    daysRemaining: 0,
    status: 'expired',
    assignedTrainer: 'Entr. David Montoya',
    emergencyContact: 'Paola Morales (Esposa)',
    emergencyPhone: '3213344556',
    bloodType: 'B+',
    routineTitle: 'Fase 1: Readaptación de Fuerza & Movilidad Lumbar',
    routineGoals: 'Fortalecimiento de zona media y aumento de masa muscular en tren inferior.',
    nutritionOverview: 'Plan nutricional suspendido temporalmente por vencimiento de suscripción.',
    records: [
      {
        id: 'rec_3_1',
        memberId: 'mem_3',
        date: '2026-07-10',
        weightKg: 88.0,
        heightCm: 175,
        bodyFatPct: 24.2,
        muscleMassKg: 36.5,
        chestCm: 104,
        waistCm: 94,
        bicepCm: 36,
        notes: 'Evaluación de ingreso con molestia lumbar leve en flexión prolongada.',
        evaluator: 'Lic. David Montoya',
      },
      {
        id: 'rec_3_2',
        memberId: 'mem_3',
        date: '2026-08-10',
        weightKg: 86.4,
        heightCm: 175,
        bodyFatPct: 22.8,
        muscleMassKg: 37.1,
        chestCm: 105,
        waistCm: 91,
        bicepCm: 36.5,
        notes: 'Molestia lumbar superada. Mejora en pesos muertos guiados.',
        evaluator: 'Lic. David Montoya',
      },
    ],
    payments: [
      {
        id: 'pay_3_1',
        memberId: 'mem_3',
        memberName: 'Andrés Felipe Morales',
        amount: 35,
        date: '2026-08-10',
        daysAdded: 30,
        method: 'Efectivo',
        receiptNumber: 'REC-2026-0610',
        notes: 'Pago Mensualidad Base en recepción física',
      },
    ],
  },
  {
    id: 'mem_4',
    cedula: '1030201040',
    name: 'Valentina Castro Vega',
    phone: '3186549871',
    email: 'valentina.castro@email.com',
    birthDate: '2001-09-14',
    planId: 'plan-personalizado-premium',
    planName: 'Plan Personalizado Premium',
    membershipStart: '2026-09-10',
    membershipEnd: '2026-10-10',
    daysRemaining: 18,
    status: 'active',
    assignedTrainer: 'Prof. Óscar Arias (Head Coach)',
    emergencyContact: 'Martha Vega (Madre)',
    emergencyPhone: '3109988776',
    bloodType: 'O-',
    routineTitle: 'Fase 4: Fuerza Potencia & Glúteo / Isquiotibiales',
    routineGoals: 'Desarrollo de fuerza en sentadilla profunda y empujes de cadera (Hip Thrust).',
    nutritionOverview: 'Plan de alimentación por intercambios, 120g de proteína de alto valor biológico.',
    records: [
      {
        id: 'rec_4_1',
        memberId: 'mem_4',
        date: '2026-08-11',
        weightKg: 58.2,
        heightCm: 162,
        bodyFatPct: 21.0,
        muscleMassKg: 26.4,
        chestCm: 86,
        waistCm: 65,
        bicepCm: 25.5,
        notes: 'Gran nivel técnico en levantamientos básicos. Gran activación neuromuscular.',
        evaluator: 'Prof. Óscar Arias',
      },
      {
        id: 'rec_4_2',
        memberId: 'mem_4',
        date: '2026-09-11',
        weightKg: 59.0,
        heightCm: 162,
        bodyFatPct: 20.1,
        muscleMassKg: 27.2,
        chestCm: 87,
        waistCm: 64.5,
        bicepCm: 26.0,
        notes: 'Ganancia neta de masa muscular magra (+800g). Mantener progresiones.',
        evaluator: 'Prof. Óscar Arias',
      },
    ],
    payments: [
      {
        id: 'pay_4_1',
        memberId: 'mem_4',
        memberName: 'Valentina Castro Vega',
        amount: 80,
        date: '2026-09-10',
        daysAdded: 30,
        method: 'Tarjeta',
        receiptNumber: 'REC-2026-0925',
        notes: 'Plan Personalizado Premium Mensual',
      },
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AccessLog[] = [
  {
    id: 'log_1',
    memberId: 'mem_1',
    memberName: 'Carlos Andrés Rodríguez',
    method: 'Código QR',
    timestamp: '2026-09-22 07:14:22',
    ip: '186.84.92.105',
    device: 'Torno Acceso 1 (Lector QR Óptico)',
    status: 'Permitido (Activo)',
  },
  {
    id: 'log_2',
    memberId: 'mem_4',
    memberName: 'Valentina Castro Vega',
    method: 'Código QR',
    timestamp: '2026-09-22 07:45:10',
    ip: '186.84.92.105',
    device: 'Torno Acceso 2 (Lector QR Óptico)',
    status: 'Permitido (Activo)',
  },
  {
    id: 'log_3',
    memberId: 'mem_2',
    memberName: 'Mariana Gómez Serna',
    method: 'Cédula',
    timestamp: '2026-09-22 08:02:44',
    ip: '186.84.92.110',
    device: 'Terminal Recepción Principal',
    status: 'Permitido (Próximo a Vencer)',
  },
  {
    id: 'log_4',
    memberId: 'mem_3',
    memberName: 'Andrés Felipe Morales',
    method: 'Cédula',
    timestamp: '2026-09-22 08:30:19',
    ip: '186.84.92.110',
    device: 'Terminal Recepción Principal',
    status: 'Denegado (En Mora)',
  },
  {
    id: 'log_5',
    memberId: 'staff_master',
    memberName: 'Óscar Arias (Administrador General)',
    method: 'QR Admin + PIN',
    timestamp: '2026-09-22 08:40:02',
    ip: '190.144.15.82',
    device: 'Panel Administrativo Staff (Next.js)',
    status: 'Acceso Staff Autorizado',
  },
];
